### ISSUE TITLE
Make command not working on OSX

### ISSUE THREAD

**Issue by mayankwadhwa** [AndreMiras/EtherollApp#119]
i am getting the following on my mac  sierra 
```
make: lsb_release: Command not found
test -d venv || virtualenv -p python3 venv
/bin/sh: virtualenv: command not found
make: *** [virtualenv] Error 127

```

**Comment by AndreMiras** [comment]
Thanks for creating a ticket for it. I haven't played that much with macOS yet, but it's in the pipe. I can increase the prio if I have demand.
For now, do you know how to overcome or do you need assistance?

**Comment by mayankwadhwa** [comment]
Thank you for the reply,I found the solution actually i didn't have virtual env installed
