### ISSUE TITLE
[BUG] When I click on the Roll button, the Etheroll application crashes.

### ISSUE THREAD

**Issue by sargoon** [AndreMiras/EtherollApp#136]
**Expected behavior**
The **Roll** button is the most important button of the Etheroll application and it should work properly.

**Actual behavior**

When I tried to click on **Roll** button in Etheroll, the application crashes immediately.

How to reproduce

1. Open the Etheroll app.
2. Click on the **Roll** button.
3. You will see that the application crashes immediately.

* App version: 2019.0217
* Operating system: Android 7.0

**Recording Of The Bug**
![BlackFantasticGentoopenguin-small](https://user-images.githubusercontent.com/34961616/56824725-eda97b80-685f-11e9-98c5-ecb5e38ffbee.gif)

**Logcat Report**
`E/InputDispatcher( 2104): channel 'c082f13 com.github.andremiras.etheroll/org.kivy.android.PythonActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
E/InputDispatcher( 2104): channel '8b1245c com.github.andremiras.etheroll/org.kivy.android.PythonActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
E/InputDispatcher( 2104): channel '6a7f79f com.github.andremiras.etheroll/org.kivy.android.PythonActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
`

**Comment by AndreMiras** [comment]
That should also be fixed in the last release https://github.com/AndreMiras/EtherollApp/releases/download/v2019.0426/etheroll-2019.0426-debug.apk

**Comment by sargoon** [comment]
Yeah, everything is OK with 2019.0426 version, thank you for your interest!

**Comment by AndreMiras** [comment]
Awesome, thanks for bug reporting!
