### ISSUE TITLE
[BUG] When I click on the Settings, the app crashes immediately.

### ISSUE THREAD

**Issue by sargoon** [AndreMiras/EtherollApp#137]
**Expected behavior**
In order to set the application's settings, users must access the **Settings** section without any error.

**Actual behavior**

When I click on the **Settings**, the Etheroll application crashes immediately.

How to reproduce

1. Open the Etheroll app.
2. Click on the Wrapper menu and select the **Settings** section.
3. You will see that the application crashes immediately.

* App version: 2019.0217
* Operating system: Android 7.0

**Recording Of The Bug**
![HighDishonestEskimodog-small](https://user-images.githubusercontent.com/34961616/56825103-e9ca2900-6860-11e9-985c-11c09cd0ddb8.gif)

**Logcat Report**
`E/InputDispatcher( 2104): channel '87123a2 com.github.andremiras.etheroll/org.kivy.android.PythonActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
E/InputDispatcher( 2104): channel 'ec4fb80 com.github.andremiras.etheroll/org.kivy.android.PythonActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
E/InputDispatcher( 2104): channel '129983c com.github.andremiras.etheroll/org.kivy.android.PythonActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
`

**Comment by AndreMiras** [comment]
Thank you for the bug report!
This is all related to #133 and #134 I'm working on an [early draft fix](https://github.com/AndreMiras/EtherollApp/commit/c2f62b700f113537163603e5bd91cacf087724a3) if you want to give it a try:
https://github.com/AndreMiras/EtherollApp/releases/download/v20190418-debug-133/etheroll-2019.0418-debug-issue-133.apk

**Comment by sargoon** [comment]
Understood, thank you very much for your message! Have a good luck, I will check the link you have provided.

**Comment by AndreMiras** [comment]
The fix looks OK so I made an official release with it:
https://github.com/AndreMiras/EtherollApp/releases/download/v2019.0426/etheroll-2019.0426-debug.apk
Could you give it a try and let me know?

**Comment by sargoon** [comment]
Thank you for the new version! Now I can access the settings section, I can also click the roll button without any errors, thanks!
