### ISSUE TITLE
BUG:[Etheroll v2019.0217]The application crashes when setting option

### ISSUE THREAD

**Issue by 44asad** [AndreMiras/EtherollApp#140]
### Expected behavior

I expected that the application should not be crash when i click on the setting option.

### Actual behavior

After configure the application when i click on setting option, the application is crash you can see in bug video properly
### How to reproduce
* Download and open the application

* click on setting option 

* Note the Bug
### Information
Browser/App version: 2019.0217

Operating system: 6.0.1

### Recording Of The Bug
https://youtu.be/Y9Smua8ioFc

**Comment by AndreMiras** [comment]
You guys are making awesome bug reports, the videos are always super helpful!
This bug has been reported in https://github.com/AndreMiras/EtherollApp/issues/137 it's solved in the last release `v2019.0426`. I'm not sure why F-Droid doesn't have it deployed yet.
Until then you can try to grab it from GitHub:
https://github.com/AndreMiras/EtherollApp/releases/download/v2019.0426/etheroll-2019.0426-debug.apk
