### ISSUE TITLE
How to export?

### ISSUE THREAD

**Issue by PC-Admin** [AndreMiras/EtherollApp#146]
Sorry for the noob question, i sent eth to a wallet i created with etheroll, i seem to be unable to import it into 'WallETH', the android wallet i have.

What mobile wallet software will import this key easily?

**Comment by PC-Admin** [comment]
MyCrypto wallet was able to import key file.

**Comment by AndreMiras** [comment]
It's actually not a newb question and we have some task to help with transferring out.
This is will probably be my next priority very soon.
Glad you got it working, thanks for updating us on it.
