### ISSUE TITLE
Broken F-Droid update

### ISSUE THREAD

**Issue by AndreMiras** [AndreMiras/EtherollApp#155]
F-Droid auto update is currently getting a 404 because it's pointing to the old version URL. See https://f-droid.org/wiki/index.php?title=checkupdates_1568932756&redirect=no
`https://raw.githubusercontent.com/AndreMiras/EtherollApp/develop/src/version.py`
See https://gitlab.com/fdroid/fdroiddata/blob/9426b69f/metadata/com.github.andremiras.etheroll.yml
This URL should instead be `https://raw.githubusercontent.com/AndreMiras/EtherollApp/develop/src/etherollapp/version.py` since we moved under the `etherollapp` namespace recently.
Also the ndk should manually be updated to `r19c` since the auto update won't catch that. Note that F-Droid doesn't have `r19b` available.

**Comment by AndreMiras** [comment]
Pull request is ready and pending https://gitlab.com/fdroid/fdroiddata/merge_requests/5526
And actually NDK should be updated after this release as the change are still unreleased in develop.

**Comment by AndreMiras** [comment]
The pull request was merged, let's keep the ticket open until v2019.0911 gets released to F-Droid.
Let's keep an eye on the apps build logs
https://f-droid.org/wiki/index.php?title=Special:RecentChanges&days=7&from=&hidebots=0&hideanons=1&hideliu=1

**Comment by AndreMiras** [comment]
Built successfully https://f-droid.org/wiki/page/com.github.andremiras.etheroll/lastbuild_721202811

**Comment by Pi-Rr** [comment]
It did work, I could update the app from F-Droid, thanks!

**Comment by licaon-kter** [comment]
And again fails at https://f-droid.org/wiki/page/com.github.andremiras.etheroll/lastbuild_721203001

**Comment by AndreMiras** [comment]
Thanks @licaon-kter for the heads up. Yes I was expecting it to fail at least because of https://github.com/kivy/python-for-android/pull/1986 and https://github.com/AndreMiras/EtherollApp/commit/6027ad45dc5e22c5c81009bf543b1b7e8dd192ad.
But I didn't get a chance to look into it this weekend. I'll hopefully this week.
I've just created a dedicated task for follow up https://github.com/AndreMiras/EtherollApp/issues/167

**Comment by AndreMiras** [comment]
@licaon-kter FYI I've made an upstream PR that should fix the build, feel free to give it a thumb up.
https://gitlab.com/fdroid/fdroiddata/merge_requests/5897
