### ISSUE TITLE
Logo design proposal 

### ISSUE THREAD

**Issue by maaudrana** [AndreMiras/EtherollApp#92]
Hallo 
Great know to know about this projects but their is no logo for this projects.I am a graphics designer and wants to make a logo for this projects.if you have any requirements or idea then let me know.its free for any open source projects.
Thank you.

**Comment by AndreMiras** [comment]
How awesome is that, thank you so much @maaudrana !
The design is definitely my weak point :smile: 
There actually is a logo that I borrowed from the official site. Currently it's just used for the APK icon and splash screen. But I could also use it in GitHub and within the app.

[![icon](https://raw.githubusercontent.com/AndreMiras/EtherollApp/develop/docs/images/icon.png)](https://github.com/AndreMiras/EtherollApp/blob/develop/docs/images/icon.png)
[![logo](https://raw.githubusercontent.com/AndreMiras/EtherollApp/develop/docs/images/etheroll-logo.png)](https://github.com/AndreMiras/EtherollApp/blob/develop/docs/images/etheroll-logo.png)

But I'm totally open to new ideas. I have to say I loe what they proposed for the new design https://etheroll.wordpress.com/2018/04/17/today-we-are-proud-to-announce-the-release-of-our-new-ui-ux/ and I would love to implement it.

**Comment by maaudrana** [comment]
hi here is my design which one of your choice tells me that I'll give you that source file. If you think something needs to be changed then you can tell me I'll change.

![er-01](https://user-images.githubusercontent.com/34313493/40651732-3ea860fe-6358-11e8-932a-1dfb9387297a.jpg)
